[tool.black]
line-length = 88
target-version = ["py39", "py310", "py311"]

[tool.isort]
profile = "black"
line_length = 88

[ruff]
line-length = 88
target-version = "py39"
select = ["E", "F"]
ignore = ["W"]